import type { Metadata } from "next";
import { Montserrat, Montserrat_Alternates, Geist_Mono } from "next/font/google";
import Header from "@/components/header";
import "./globals.css";

  const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"],
  });

  const montserratAlternates = Montserrat_Alternates({
    variable: "--font-montserrat-alternates",
    weight: ["900"],
    subsets: ["latin"],
  });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${geistMono.variable} ${montserratAlternates.variable} antialiased`}
    >
      <body className="flex flex-col gradient-background">
        <Header />
        {children}
      </body>
    </html>
  );
}
